services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: maianhhoang31072003/linxtalk-be:latest
    container_name: linxtalk-be
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - linxtalk-network

networks:
  linxtalk-network:
    driver: bridge
