services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linxtalk-be
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION:2592000000}
    restart: unless-stopped
    networks:
      - linxtalk-network


networks:
  linxtalk-network:
    driver: bridge

